# Generated by Django 3.0.4 on 2020-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
            ],
        ),
    ]
