# Generated by Django 3.0.4 on 2020-03-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
            ],
        ),
    ]
